set -s default-terminal tmux-256color

set -s escape-time 0

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Enable focus events
set -g focus-events on

# Status line
set -g status-style fg=black,bg=default

# Command line and messages
set -g message-style fg=black,bg=default

# Left side of status, empty, so there is only window list
set -g status-left ""

# Right side of status
set -g status-right "#S"

# Current window
set -g window-status-current-style fg=black,bold

# Execute
set -g prefix C-x
unbind-key C-b

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key -n M-1 selectw -t 1
bind-key -n M-2 selectw -t 2
bind-key -n M-3 selectw -t 3
bind-key -n M-4 selectw -t 4
