require "esmantovich.options"
require "esmantovich.keymaps"
require "esmantovich.plugins"
vim.g.ayucolor = "light"
require "esmantovich.colorscheme"
require "esmantovich.cmp"
require "esmantovich.lsp"
require "esmantovich.treesitter"
require "esmantovich.autopairs"
-- require "esmantovich.comment"
require "esmantovich.gitsigns"
-- require "esmantovich.transparentbg"
require "esmantovich.nvim-tree"
require "esmantovich.lualine"
